name: ESGI Micro CI Frontend

on: [push, pull_request]

jobs:
  build:
    name: Build Angular Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v1

      - name: Use Node.js LTS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Build Project
        run: npm run build

  deploy:
    name: Deploy to Heroku Platform
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Project
        uses: actions/checkout@v1

      - name: Heroku Login
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:login

      - name: Heroku Build & Push Docker Image
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:push -a micro-ci-al2 web

      - name: Heroku Deploy to Production
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:release -a micro-ci-al2 web
